### ISSUE TITLE
Show FsPath instance

### ISSUE THREAD

**Issue by phadej** [haskell-hvr/paths#1]
lack of it is very inconvinient

**Comment by hvr** [comment]
and to what String shall it serialize? shall there ever be a corresponding `Read` instance?

**Comment by phadej** [comment]
There couldn't be `Read` instance, as `FsRoot` is open universe. It could print something like `FsPath @CWD "rawcontents"`, and the `CWD` could come either from new member of `FsRoot`, or `Typeable` superclass of `FsRoot` (which shouldn't be a problem)

**Comment by hvr** [comment]
@phadej  I don't have any strong opinion about which Show serialization to go for specifically; the TypeApplication style one you're suggesting sounds good to me if it's easy to implement
