### ISSUE TITLE
Add `basePath` to `FsRoot` class

### ISSUE THREAD

**Issue by phadej** [haskell-hvr/paths#2]
Self explanatory.

**Comment by hvr** [comment]
So you're suggesting to add

```
class FsRoot root where
   -- ...
   rootPath :: Path root
```

?

Makes sense I guess; I'm however a bit worried that the term `rootPath` is confusing for e.g. `rootPath :: Path CWD`

Make call it something more neutral such as `basePath`?

**Comment by phadej** [comment]
`basePath` is fine. It doesn't clash with anything in `filepath` or `directory` either.
