### ISSUE TITLE
rename getDirectoryContents to listDirectory

### ISSUE THREAD

**Issue by phadej** [haskell-hvr/paths#4]
That will be consistent with `directory` naming

**Comment by hvr** [comment]
Sounds good; I suspect the name `getDirectoryContents` was picked (NB: this is code I inherited from hackage-security) because `listDirectory` was added to `directory` at some later point

only question to me is whether to leave in place an old alias w/ a DEPRECATE pragma

**Comment by phadej** [comment]
I see two options:
- Change it to do what it does in `directory`, i.e. include `.` and `..`
- or (imho better) just drop it

Latter is better, as these would be hard to notice change. I don't remember ever wanting `getDirectoryContents` behavior, so won't be missing it.

**Comment by hvr** [comment]
I've got no objection to just dropping it without leaving any alias behind; I've got a dozen internal projects which rely on `paths` and I'll know rightaway how to fix em up when upgrading to a newer version of `paths`
