### ISSUE TITLE
Why System.Path.IO re-export System.IO stuff, which doesn't have any FilePath stuff?

### ISSUE THREAD

**Issue by phadej** [haskell-hvr/paths#5]
Convinience here is a wrong reason. :S

**Comment by hvr** [comment]
The problem the reexport tried to address was the annoyance that `import System.IO` drags in a couple of  functions with `FilePath`s; and if otoh you try using the `Handle`-related operations from  `System.Path.IO` you will inevitably require some additional operations to be able to make use of `Handle`s.

What problem specifically are you worrying about by having those hand-picked small set of reexports here?

**Comment by phadej** [comment]
The problem I see, is that `System.Path.IO` is a "kitchen sink" module. I'd split it into three:

- `bytestring` and `text` reading&writing functions
- `directory` wrappers
- `withFile` and `openTempFile` + `System.IO` re-exports.

And maybe then `System.Path.IO` could re-export all three of these.

**Comment by hvr** [comment]
I very much like the split-up you're suggesting (including the reexporting parent module) :-)
